import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Sidebar from "@/components/Sidebar";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import prisma from "@/db/prisma";
import { redirect } from "next/navigation";
import { UserPlanProvider } from "@/components/providers/UserPlanProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function ProtectedLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // Restringir acesso
  const { getUser } = getKindeServerSession();
  const user = await getUser();
  const prismaUser = await prisma.user.findFirst({
    where: { email: user?.email ?? undefined }
  });

  if (prismaUser?.plan === "free") {
    console.log("You must be a premium member to access this area!");
    redirect("/");
  }

  const userPlan = await prismaUser?.plan;

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <UserPlanProvider userPlan={userPlan ?? null}>
          <div className="h-screen flex">
            <Sidebar />
            <main className="flex-1 h-full overflow-auto bg-neutral-900 text-white">
              {children}
            </main>
          </div>
        </UserPlanProvider>
      </body>
    </html>
  );

}
